# Generated by Django 6.0.7 on 2026-08-03 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSKLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hsk_levels/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HSK Level',
                'verbose_name_plural': 'HSK Levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=1, unique=True)),
                ('practice_writing', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('hsk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='learning.hsklevel')),
            ],
            options={
                'ordering': ['hsk_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('hsk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.hsklevel')),
            ],
            options={
                'ordering': ['hsk_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('hsk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_points', to='learning.hsklevel')),
                ('lessons', models.ManyToManyField(blank=True, related_name='grammar_points', to='learning.lesson')),
            ],
            options={
                'ordering': ['hsk_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('flashcard', 'Flashcard'), ('multiple_choice', 'Multiple Choice'), ('matching', 'Matching'), ('typing', 'Typing'), ('listening', 'Listening'), ('drag_drop', 'Drag & Drop'), ('word_tile', 'Word Tile')], max_length=30)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('raw_score', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('hsk_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_results', to='learning.hsklevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsk_id', models.PositiveIntegerField(db_index=True)),
                ('simplified', models.CharField(db_index=True, max_length=50)),
                ('traditional', models.CharField(blank=True, max_length=50)),
                ('pinyin', models.CharField(db_index=True, max_length=100)),
                ('pinyin_plain', models.CharField(db_index=True, max_length=100)),
                ('meaning', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hsk_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='learning.hsklevel')),
                ('lessons', models.ManyToManyField(blank=True, related_name='vocabulary', to='learning.lesson')),
            ],
            options={
                'ordering': ['hsk_level__level', 'hsk_id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizresult')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='learning.vocabulary')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastered', models.BooleanField(default=False)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_words', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by', to='learning.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_words', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='learning.vocabulary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('pinyin', models.TextField()),
                ('translation', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='learning.vocabulary')),
            ],
            options={
                'ordering': ['vocabulary', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('hsk_level', 'order'), name='unique_lesson_order_per_hsk'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['hsk_level'], name='learning_vo_hsk_lev_d2f69b_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['simplified'], name='learning_vo_simplif_9ba446_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['traditional'], name='learning_vo_traditi_ef1bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['pinyin'], name='learning_vo_pinyin_c9a5b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('hsk_level', 'hsk_id'), name='unique_vocab_per_level'),
        ),
        migrations.AddIndex(
            model_name='learnedword',
            index=models.Index(fields=['user', 'review_date', 'mastered'], name='learning_le_user_id_a44792_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnedword',
            constraint=models.UniqueConstraint(fields=('user', 'vocabulary'), name='unique_learned_word'),
        ),
        migrations.AddConstraint(
            model_name='favoriteword',
            constraint=models.UniqueConstraint(fields=('user', 'vocabulary'), name='unique_favorite_word'),
        ),
    ]
