# Generated by Django 6.0.7 on 2026-08-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='typing_mode',
            field=models.CharField(blank=True, choices=[('meaning_to_chinese', 'Meaning to Chinese'), ('chinese_to_pinyin', 'Chinese to Pinyin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
