# Generated by Django 6.0.7 on 2026-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_quizresult_typing_mode_alter_quizresult_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='raw_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
